### ISSUE TITLE
Problem when trying to run tar()

### ISSUE THREAD

**Issue by lowks** [amoffat/sh#144]
I get this output when I try to use the tar command to tar up a directory:

>>> from sh import tar
>>> tar('-cvzf test2.tar.gz /home/lowks/puke/puke2_test/test')
Exit code is this 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lowks/virtualenv/puke2/lib/python2.7/site-packages/sh.py", line 727, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/lowks/virtualenv/puke2/lib/python2.7/site-packages/sh.py", line 291, in __init__
    self.wait()
  File "/home/lowks/virtualenv/puke2/lib/python2.7/site-packages/sh.py", line 295, in wait
    self._handle_exit_code(self.process.wait())
  File "/home/lowks/virtualenv/puke2/lib/python2.7/site-packages/sh.py", line 310, in _handle_exit_code
    self.process.stderr
sh.ErrorReturnCode_2: 

  RAN: '/bin/tar -cvzf test2.tar.gz /home/lowks/puke/puke2_test/test'

  STDOUT:

  STDERR:
/bin/tar: Cowardly refusing to create an empty archive
Try `/bin/tar --help' or `/bin/tar --usage' for more information.

Is this a bug ?

**Comment by mandarvaze** [comment]
Which (documentation) repo should I contribute to - so that the above is listed as an example ?

**Comment by amoffat** [comment]
@mandarvaze fork the https://github.com/amoffat/sh/tree/gh-pages branch and open the PR against it

**Comment by mandarvaze** [comment]
Submitted a PR : https://github.com/amoffat/sh/pull/239

**Comment by amoffat** [comment]
good stuff @mandarvaze
