### ISSUE TITLE
Commands fail due to logging when there are formatting characters in the command line

### ISSUE THREAD

**Issue by tesh11** [amoffat/sh#212]
The command format string has % characters in it and it causes logging to fail:
```
<Command '/usr/bin/git --no-pa...(53 more)' call_args {'bg': False, 'timeo...(476 more)>.<Process 30207 ['/usr/bin/git', '--no-pager', 'log', '-1', '--pretty=format:%H%n%aN%n%ae%n%cN%n%ce%n%s']>: started process ()
Traceback (most recent call last):
  File "/home/rof/.virtualenv/bin/coveralls", line 9, in <module>
    load_entry_point('python-coveralls==2.4.4', 'console_scripts', 'coveralls')()
  File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/coveralls/__init__.py", line 89, in wear
    git=gitrepo(args.base_dir),
  File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/coveralls/repository.py", line 9, in gitrepo
    gitlog = sh.git('--no-pager', 'log', '-1', pretty="format:%s" % FORMAT).split('\n', 5)
  File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/sh.py", line 1020, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/sh.py", line 482, in __init__
    self.call_args, pipe)
  File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/sh.py", line 1350, in __init__
    self.log.debug("started process")
  File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/sh.py", line 384, in debug
    self.log.debug(self._format_msg(msg, *args))
  File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/sh.py", line 372, in _format_msg
    return msg % args
TypeError: not enough arguments for format string
```

**Comment by tesh11** [comment]
That seems to fix the issue for me. Thanks!
