### ISSUE TITLE
Getting Runtime error

### ISSUE THREAD

**Issue by gau1991** [amoffat/sh#234]
Hi, 
I am trying to use following code:
My Environment is Python 3, Ubuntu 14.04,
I using following code:

```
       global apt_get
        apt_get = apt_get.bake("-y")
        try:
            for line in apt_get.update(_iter=True):
                print(line)
        except ErrorReturnCode as e:
            print("Error")
```

Getting exception as

```
Hit http://repo.percona.com trusty InRelease
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sh-1.11-py3.4.egg/sh.py", line 1484, in output_thread
    done = stream.read()
  File "/usr/local/lib/python3.4/dist-packages/sh-1.11-py3.4.egg/sh.py", line 1974, in read
    self.write_chunk(chunk)
  File "/usr/local/lib/python3.4/dist-packages/sh-1.11-py3.4.egg/sh.py", line 1957, in write_chunk
    self.pipe_queue().put(chunk)
  File "/usr/lib/python3.4/queue.py", line 148, in put
    self.not_empty.notify()
  File "/usr/lib/python3.4/threading.py", line 341, in notify
    waiters_to_notify = _deque(_islice(all_waiters, n))
RuntimeError: deque mutated during iteration
```

**Comment by amoffat** [comment]
Interesting, I cannot reproduce this behavior.  I'm on Ubuntu 14.10, python 3.4, sh 1.11.  It appears to be a python bug, can you try with another version of python?
