### ISSUE TITLE
Doesn't seem to work in bpython shell

### ISSUE THREAD

**Issue by hvishwanath** [amoffat/sh#249]
```sh``` seems to be infinitely blocking when executed from within a "bpython" shell.

* Using bpython (```pip install bpython```)
```
/t/hkv git:master ❯❯❯ bpython
bpython version 0.14.1 on top of Python 2.7.6 /usr/bin/python
>>> from sh import git
>>> git.init()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/hvishwanath/.virtualenvs/libpaas/lib/python2.7/site-packages/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/hvishwanath/.virtualenvs/libpaas/lib/python2.7/site-packages/sh.py", line 486, in __init__
    self.wait()
  File "/home/hvishwanath/.virtualenvs/libpaas/lib/python2.7/site-packages/sh.py", line 493, in wait
    exit_code = self.process.wait()
  File "/home/hvishwanath/.virtualenvs/libpaas/lib/python2.7/site-packages/sh.py", line 1601, in wait
    pid, exit_code = os.waitpid(self.pid, 0) # blocks
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsiesfrontend/coderunner.py", line 164, in sigint_handler
    raise KeyboardInterrupt()
KeyboardInterrupt

```
* The same thing with normal python shell
```
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sh import git
>>> git.init()
Reinitialized existing Git repository in /tmp/hkv/.git/
```

**Comment by amoffat** [comment]
BPython doesn't seem to have a lot of traction right now.  I will not fix this but, I will merge a PR that does fix it.
