### ISSUE TITLE
long line truncated in stdout ?

### ISSUE THREAD

**Issue by aboudreault** [amoffat/sh#282]
It looks like long line are truncated, which make a command fails.

```
sh.grep(sh.ps('aux'), "-ie", "java.*Cassandra")
```

while this shell command works well: 

```
 ps aux | grep -ie "java.*Cassandra"
```

Anything I should know about the line truncated?

**Comment by amoffat** [comment]
```python
sh.grep(sh.ps('aux', _piped=True), "-ie", "java.*Cassandra")
```
works for me.  without `_piped=True`, the inner call evaluates to a string, so you're trying to grep a string which of course fails.

**Comment by snordhausen** [comment]
I ran into a similar problem some time ago, but not with the sh module. After hours of debugging, it turned out there was some environment variable that convinced grep (or was it ps?) that my "terminal" was only 80 characters wide. Since the program tried to fit into my "terminal", it truncated the output lines.

So I recommend you take a look at how the environment variables differ between your shell and your usage of the sh module.

**Comment by aboudreault** [comment]
I just noticed that my command works in the python interpreter, but not in the ipython interpreter.

Your version @amoffat works well everywhere. Thanks

**Comment by aboudreault** [comment]
oh, I thought it was working but no. The following code crash at the sh.grep line when subprocess succeed.

```
def find_cassandra_pid():
    cmd = "ps aux | grep -ie 'java.*Cassandra' | grep -v grep | awk '{print $2}'"
    proc = subprocess.Popen(cmd,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT,
                            shell=True)
    output = proc.communicate()
    if proc.returncode != 0:
        raise AssertionError("Cannot find cassandra pid")

    print output[0]
    print sh.grep(sh.ps('aux', _piped=True), "-ie", "java.*Cassandra")

```

```
29754

!!! Parallel execution exception under host u'127.0.0.1':
Process 127.0.0.1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aboudreault/git/cstar/cstar_perf/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 242, in inner
    submit(task.run(*args, **kwargs))
  File "/home/aboudreault/git/cstar/cstar_perf/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/aboudreault/git/cstar/cstar_perf/venv/local/lib/python2.7/site-packages/fabric/decorators.py", line 181, in inner
    return func(*args, **kwargs)
  File "/home/aboudreault/git/cstar/cstar_perf/tool/cstar_perf/tool/fab_flamegraph.py", line 41, in start_perf_agent
    cassandra_pid = common.find_cassandra_pid()
  File "/home/aboudreault/git/cstar/cstar_perf/tool/cstar_perf/tool/fab_common.py", line 671, in find_cassandra_pid
    print sh.grep(sh.ps('aux', _piped=True), "-ie", "java.*Cassandra")
  File "/home/aboudreault/git/cstar/cstar_perf/venv/local/lib/python2.7/site-packages/sh.py", line 1021, in __call__
Traceback (most recent call last):
  File "/home/aboudreault/git/cstar/cstar_perf/venv/bin/cstar_perf_stress", line 9, in <module>
    load_entry_point('cstar-perf.tool==1.0', 'console_scripts', 'cstar_perf_stress')()
  File "/home/aboudreault/git/cstar/cstar_perf/tool/cstar_perf/tool/stress_compare.py", line 275, in main
    stress_compare(**cfg)
  File "/home/aboudreault/git/cstar/cstar_perf/tool/cstar_perf/tool/stress_compare.py", line 155, in stress_compare
    execute(flamegraph.start_perf_agent)
  File "/home/aboudreault/git/cstar/cstar_perf/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 412, in execute
    ran_jobs = jobs.run()
  File "/home/aboudreault/git/cstar/cstar_perf/venv/local/lib/python2.7/site-packages/fabric/job_queue.py", line 168, in run
    self._fill_results(results)
  File "/home/aboudreault/git/cstar/cstar_perf/venv/local/lib/python2.7/site-packages/fabric/job_queue.py", line 191, in _fill_results
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/aboudreault/git/cstar/cstar_perf/venv/local/lib/python2.7/site-packages/sh.py", line 486, in __init__
    datum = self._comms_queue.get_nowait()
    self.wait()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 152, in get_nowait
  File "/home/aboudreault/git/cstar/cstar_perf/venv/local/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/aboudreault/git/cstar/cstar_perf/venv/local/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    return self.get(False)
    raise exc(self.ran, self.process.stdout, self.process.stderr)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 135, in get
ErrorReturnCode_1: 

  RAN: '/bin/grep -ie java.*Cassandra'

  STDOUT:


  STDERR:

    res = self._recv()
TypeError: ('__init__() takes exactly 4 arguments (2 given)', <class 'sh.ErrorReturnCode_1'>, (u"\n\n  RAN: '/bin/grep -ie java.*Cassandra'\n\n  STDOUT:\n\n\n  STDERR:\n",))

```

**Comment by amoffat** [comment]
I'm seeing a lot of Fabric and Multiprocessing in that stack trace.  Try running it on your local machine first and see if it works.  If it does work, then we can say that the issue is an interaction between third party modules.

**Comment by aboudreault** [comment]
Very simple script: https://gist.github.com/aboudreault/19ba5e7b918b32a344cd

output:

```
aboudreault@kovaro:~/git/cstar/cassandra$ python ~/test.py 
16839

Traceback (most recent call last):
  File "/home/aboudreault/test.py", line 18, in <module>
    find_cassandra_pid()
  File "/home/aboudreault/test.py", line 16, in find_cassandra_pid
    print sh.grep(sh.ps('aux', _piped=True), "-ie", "java.*Cassandra")
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 486, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/bin/grep -ie java.*Cassandra'

  STDOUT:


  STDERR:
```

ps aux|grep -ie "java.*Cassandra" output:

```
aboudreault@kovaro:~/git/cstar/cassandra$ ps aux|grep -ie "java.*Cassandra"
aboudre+ 16839  3.1 27.1 5960448 4430332 ?     SLl  12:52   0:14 /home/aboudreault/fab/java/bin/java -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=127.0.0.1 -Xloggc:/home/aboudreault/fab/cassandra/logs/gc.log -XX:+PreserveFramePointer -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=1 -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSWaitDuration=10000 -XX:+CMSParallelInitialMarkEnabled -XX:+CMSEdenChunksRecordAlways -XX:+CMSClassUnloadingEnabled -Xms3988M -Xmx3988M -Xmn800M -XX:+UseCondCardMark -ea -Xss256k -XX:+AlwaysPreTouch -XX:-UseBiasedLocking -XX:StringTableSize=1000003 -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:CompileCommandFile=/home/aboudreault/fab/cassandra/bin/../conf/hotspot_compiler -javaagent:/home/aboudreault/fab/cassandra/bin/../lib/jamm-0.3.0.jar -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dcassandra.jmx.local.port=7199 -XX:+DisableExplicitGC -Djava.library.path=/home/aboudreault/fab/cassandra/bin/../lib/sigar-bin -Dlogback.configurationFile=logback.xml -Dcassandra.logdir=/home/aboudreault/fab/cassandra/bin/../logs -Dcassandra.storagedir=/home/aboudreault/fab/cassandra/bin/../data -cp /home/aboudreault/fab/cassandra/bin/../conf:/home/aboudreault/fab/cassandra/bin/../build/classes/main:/home/aboudreault/fab/cassandra/bin/../build/classes/thrift:/home/aboudreault/fab/cassandra/bin/../lib/ST4-4.0.8.jar:/home/aboudreault/fab/cassandra/bin/../lib/airline-0.6.jar:/home/aboudreault/fab/cassandra/bin/../lib/antlr-runtime-3.5.2.jar:/home/aboudreault/fab/cassandra/bin/../lib/asm-5.0.4.jar:/home/aboudreault/fab/cassandra/bin/../lib/cassandra-driver-core-3.0.0-beta1-92c4c80-SNAPSHOT-shaded.jar:/home/aboudreault/fab/cassandra/bin/../lib/commons-cli-1.1.jar:/home/aboudreault/fab/cassandra/bin/../lib/commons-codec-1.2.jar:/home/aboudreault/fab/cassandra/bin/../lib/commons-lang3-3.1.jar:/home/aboudreault/fab/cassandra/bin/../lib/commons-math3-3.2.jar:/home/aboudreault/fab/cassandra/bin/../lib/compress-lzf-0.8.4.jar:/home/aboudreault/fab/cassandra/bin/../lib/concurrentlinkedhashmap-lru-1.4.jar:/home/aboudreault/fab/cassandra/bin/../lib/disruptor-3.0.1.jar:/home/aboudreault/fab/cassandra/bin/../lib/ecj-4.4.2.jar:/home/aboudreault/fab/cassandra/bin/../lib/guava-18.0.jar:/home/aboudreault/fab/cassandra/bin/../lib/high-scale-lib-1.0.6.jar:/home/aboudreault/fab/cassandra/bin/../lib/jackson-core-asl-1.9.2.jar:/home/aboudreault/fab/cassandra/bin/../lib/jackson-mapper-asl-1.9.2.jar:/home/aboudreault/fab/cassandra/bin/../lib/jamm-0.3.0.jar:/home/aboudreault/fab/cassandra/bin/../lib/javax.inject.jar:/home/aboudreault/fab/cassandra/bin/../lib/jbcrypt-0.3m.jar:/home/aboudreault/fab/cassandra/bin/../lib/jcl-over-slf4j-1.7.7.jar:/home/aboudreault/fab/cassandra/bin/../lib/jgrapht-core-0.9.1.jar:/home/aboudreault/fab/cassandra/bin/../lib/jna-4.0.0.jar:/home/aboudreault/fab/cassandra/bin/../lib/joda-time-2.4.jar:/home/aboudreault/fab/cassandra/bin/../lib/json-simple-1.1.jar:/home/aboudreault/fab/cassandra/bin/../lib/libthrift-0.9.2.jar:/home/aboudreault/fab/cassandra/bin/../lib/log4j-over-slf4j-1.7.7.jar:/home/aboudreault/fab/cassandra/bin/../lib/logback-classic-1.1.3.jar:/home/aboudreault/fab/cassandra/bin/../lib/logback-core-1.1.3.jar:/home/aboudreault/fab/cassandra/bin/../lib/lz4-1.3.0.jar:/home/aboudreault/fab/cassandra/bin/../lib/metrics-core-3.1.0.jar:/home/aboudreault/fab/cassandra/bin/../lib/metrics-logback-3.1.0.jar:/home/aboudreault/fab/cassandra/bin/../lib/netty-all-4.0.23.Final.jar:/home/aboudreault/fab/cassandra/bin/../lib/ohc-core-0.4.2.jar:/home/aboudreault/fab/cassandra/bin/../lib/ohc-core-j8-0.4.2.jar:/home/aboudreault/fab/cassandra/bin/../lib/reporter-config-base-3.0.0.jar:/home/aboudreault/fab/cassandra/bin/../lib/reporter-config3-3.0.0.jar:/home/aboudreault/fab/cassandra/bin/../lib/sigar-1.6.4.jar:/home/aboudreault/fab/cassandra/bin/../lib/slf4j-api-1.7.7.jar
```

**Comment by amoffat** [comment]
So here's a clue...  `sh.ErrorReturnCode_1` is being raised.  According to the grep man page:

> The  exit  status is 0 if selected lines are found, and 1 if not found.  If an error occurred the exit status is 2.  (Note: POSIX error handling code should check for '2' or greater.)

So your process is not being found.  I don't have cassandra installed so I can't do the exact search, but when I do a similar star search:  `sh.grep(sh.ps('aux', _piped=True), "-ie", "google.*chrome")`, I get output.

**Comment by amoffat** [comment]
You might try messing with your grep query.  You have it quoted on the commandline, but not quoted in your script:

`grep -ie "java.*Cassandra"` vs `grep -ie java.*Cassandra`

You also might try running `sh.ps("aux")` separately and printing the output to ensure that cassandra is actually being listed there.

**Comment by aboudreault** [comment]
@amoffat My process IS being found.... see the process id printed using the same subprocess command.

**Comment by aboudreault** [comment]
It works with google-chrome since the process line is not long

**Comment by amoffat** [comment]
https://github.com/amoffat/sh/blob/master/sh.py#L745-L747

**Comment by aboudreault** [comment]
I also tried to quote the "java.*Cassandra" part without luck.

**Comment by aboudreault** [comment]
ah! That tty_size is probably what I need then.

**Comment by amoffat** [comment]
Alternatively, I just had luck with setting `_tty_out=False` on the ps command.  This keeps lines from being truncated.  Sorry, I was so focused on getting the commands straight I forgot about the original issue of truncated lines.

**Comment by amoffat** [comment]
Also, `sh.ps` seems to behave differently whether its run from a script or from a shell.  It's probably sniffing its environment and changing the output based on this.  Those are my favorite programs /s

**Comment by aboudreault** [comment]
yep! works well with _tty_out=False. Thank you for your help @amoffat very appreciated.

**Comment by amoffat** [comment]
Just some related info... http://lists.freebsd.org/pipermail/freebsd-questions/2004-October/062835.html

> Generally, if you're grepping through the output of ps(1), you want
all of the ps output to be there.  The usual idiom is:

    % ps -auxww | grep foo

**Comment by aboudreault** [comment]
Interesting.... I was not aware of that -w flag. Thank for pointing this!
