### ISSUE TITLE
Cannot run commands in the `ptpython` interpreter

### ISSUE THREAD

**Issue by riccardomurri** [amoffat/sh#293]
`sh`'s execution default seem not to be good for [ptpython][1]
(and possibly other interpreters that do TTY manipulation)::

    >>> from sh import git

    >>> git('rev-parse', 'HEAD')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/rmurri/.virtualenvs/elasticluster-dev/lib/python2.7/site-packages/sh.py", line 1021, in __call__
        return RunningCommand(cmd, call_args, stdin, stdout, stderr)
      File "/home/rmurri/.virtualenvs/elasticluster-dev/lib/python2.7/site-packages/sh.py", line 486, in __init__
        self.wait()
      File "/home/rmurri/.virtualenvs/elasticluster-dev/lib/python2.7/site-packages/sh.py", line 500, in wait
        self.handle_command_exit_code(exit_code)
      File "/home/rmurri/.virtualenvs/elasticluster-dev/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
        raise exc(self.ran, self.process.stdout, self.process.stderr)
    ErrorReturnCode_255:

      RAN: '/usr/bin/git rev-parse HEAD'

      STDOUT:

      STDERR:

      RAN: '/usr/bin/git rev-parse HEAD'

      STDOUT:

      STDERR:

Running the same command with `_tty_out=False` gives the desired
output::

    >>> git('rev-parse', 'HEAD', _tty_out=False)
    7446c8a8b4559ae4629f9a153a945fdb07d83dfe

Likewise, everything works fine under the default CPython interpreter.

[1]: https://github.com/jonathanslenders/ptpython/

**Comment by amoffat** [comment]
Interesting.  An exit code of 255 internally means there was an exception between the fork and the spawn...  https://github.com/amoffat/sh/blob/master/sh.py#L1294-L1302

**Comment by riccardomurri** [comment]
In this case, I'm more inclined to think it is related to TTY handling, e.g., the `setwinsize()` call fails.

**Comment by amoffat** [comment]
@riccardomurri I'd say go ahead and poke the author of ptpython and reference this issue.  I've confirmed it works as CPython and IPython as well, so it sounds like they may be doing something non-standard.  We can re-open this if it turns out I'm doing something incorrectly
