### ISSUE TITLE
tests assume existence of some binaries

### ISSUE THREAD

**Issue by 0-wiz-0** [amoffat/sh#347]
The tests assume that `python` and `lsof` exist.
Some distributions (like pkgsrc) only provide versioned python binaries, i.e. `python3.5`; and `lsof` may or may not be installed.

**Comment by amoffat** [comment]
I understand `lsof` not existing, but could you elaborate on python not existing as well?  The tests should only expect the python version that the test is currently running under.

**Comment by 0-wiz-0** [comment]
Most tests are fine in that regard, but some not. Here's the complete error log from the end of the test run on NetBSD 7.99.42/amd64 with python-3.5.2:
````
======================================================================
ERROR: test_importer_detects_module_name (test.ExecutionContextTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sh-1.12.7/test.py", line 2865, in test_importer_detects_module_name
    from omg import python
ImportError: cannot import name 'python'

======================================================================
ERROR: test_background_exception (test.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sh-1.12.7/test.py", line 821, in test_background_exception
    self.assertRaises(exc_to_test, p.wait) # should raise
  File "/usr/pkg/lib/python3.5/unittest/case.py", line 727, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/pkg/lib/python3.5/unittest/case.py", line 176, in handle
    callable_obj(*args, **kwargs)
  File ".../sh-1.12.7/sh.py", line 656, in wait
    self.handle_command_exit_code(exit_code)
  File ".../sh-1.12.7/sh.py", line 677, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: .../.tools/bin/ls /ofawjeofj

  STDOUT:


  STDERR:
ls: /ofawjeofj: No such file or directory


======================================================================
ERROR: test_fg (test.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sh-1.12.7/test.py", line 1550, in test_fg
    sh.python(py.name, _fg=True)
  File ".../sh-1.12.7/sh.py", line 3172, in __getattr__
    return self.__env[name]
  File ".../sh-1.12.7/sh.py", line 3049, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: python

======================================================================
ERROR: test_general_signal (test.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sh-1.12.7/test.py", line 1329, in test_general_signal
    p = python(py.name, _out=agg, _tee=True)
  File ".../sh-1.12.7/sh.py", line 1285, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File ".../sh-1.12.7/sh.py", line 638, in __init__
    self.wait()
  File ".../sh-1.12.7/sh.py", line 656, in wait
    self.handle_command_exit_code(exit_code)
  File ".../sh-1.12.7/sh.py", line 677, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/pkg/bin/python3.5 /tmp/tmpybhdngtz

  STDOUT:
0
1
2
3


  STDERR:
Traceback (most recent call last):
  File "/tmp/tmpybhdngtz", line 14, in <module>
    print(i)
  File "/tmp/tmpybhdngtz", line 8, in sig_handler
    print(10)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>


======================================================================
ERROR: test_grandchild_no_sighup (test.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sh-1.12.7/test.py", line 2444, in test_grandchild_no_sighup
    out = output_file.readlines()[0]
IndexError: list index out of range

======================================================================
ERROR: test_multiple_pipes (test.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sh-1.12.7/test.py", line 350, in test_multiple_pipes
    from sh import tr, python
ImportError: cannot import name 'python'

======================================================================
ERROR: test_ok_code (test.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sh-1.12.7/test.py", line 314, in test_ok_code
    self.assertRaises(exc_to_test, ls, "/aofwje/garogjao4a/eoan3on")
  File "/usr/pkg/lib/python3.5/unittest/case.py", line 727, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/pkg/lib/python3.5/unittest/case.py", line 176, in handle
    callable_obj(*args, **kwargs)
  File ".../sh-1.12.7/sh.py", line 1285, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File ".../sh-1.12.7/sh.py", line 638, in __init__
    self.wait()
  File ".../sh-1.12.7/sh.py", line 656, in wait
    self.handle_command_exit_code(exit_code)
  File ".../sh-1.12.7/sh.py", line 677, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: .../.tools/bin/ls /aofwje/garogjao4a/eoan3on

  STDOUT:


  STDERR:
ls: /aofwje/garogjao4a/eoan3on: No such file or directory


======================================================================
ERROR: test_signal_group (test.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sh-1.12.7/test.py", line 1997, in test_signal_group
    p, child_pid, child_pgid, parent_pid, parent_pgid = launch()
  File ".../sh-1.12.7/test.py", line 1980, in launch
    child_pid = int(next(p).strip())
  File ".../sh-1.12.7/sh.py", line 725, in next
    self.wait()
  File ".../sh-1.12.7/sh.py", line 656, in wait
    self.handle_command_exit_code(exit_code)
  File ".../sh-1.12.7/sh.py", line 677, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/pkg/bin/python3.5 /tmp/tmpkpdn1xmy

  STDOUT:


  STDERR:
Traceback (most recent call last):
  File "/tmp/tmpkpdn1xmy", line 3, in <module>
    p = sh.python("/tmp/tmpehqg5x0i", _bg=True, _new_session=False)
  File ".../sh-1.12.7/sh.py", line 3172, in __getattr__
    return self.__env[name]
  File ".../sh-1.12.7/sh.py", line 3049, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: python


======================================================================
ERROR: test_no_fd_leak (test.MiscTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sh-1.12.7/test.py", line 2570, in test_no_fd_leak
    baseline = get_num_fds()
  File ".../sh-1.12.7/test.py", line 2556, in get_num_fds
    lines = sh.lsof(p=test_pid).strip().split("\n")
  File ".../sh-1.12.7/sh.py", line 3172, in __getattr__
    return self.__env[name]
  File ".../sh-1.12.7/sh.py", line 3049, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: lsof

======================================================================
FAIL: test_threaded_with_contexts (test.MiscTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../sh-1.12.7/test.py", line 2752, in test_threaded_with_contexts
    self.assertEqual(results, correct)
AssertionError: Lists differ: [None, None] != ["('1', 'one')", "('2', 'two')"]

First differing element 0:
None
"('1', 'one')"

- [None, None]
+ ["('1', 'one')", "('2', 'two')"]

----------------------------------------------------------------------
Ran 150 tests in 53.741s

FAILED (failures=1, errors=9, skipped=1)
````

**Comment by amoffat** [comment]
Thanks for reporting, I'll look into this

**Comment by carlwgeorge** [comment]
This is affecting Fedora now too, as `/usr/bin/python` has moved to the python-unversioned-command package and is no longer installed in the default buildroot.

```
======================================================================
ERROR: test_grandchild_no_sighup (__main__.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/sh-1.12.14/test.py", line 2528, in test_grandchild_no_sighup
    out = output_file.readlines()[0]
IndexError: list index out of range
```

**Comment by amoffat** [comment]
#438 fixes this, and `lsof` has been taken care of.  This should be solved through the next release.
