### ISSUE TITLE
RunningCommand.kill() hangs when killing a script that iterates over subprocess stdout

### ISSUE THREAD

**Issue by dmitry-xnor** [amoffat/sh#383]
Or at least I think that's what's going on. Stack traces are below.

Scenario: I have a rather long running sequence of benchmarks I need to run. I use sh to drive it. I iterate over stdout of the benchmark program and write its output to both the screen and a log file. Sometimes I would like to abort the run inteactively using Ctrl+C. In that case, the child program _must_ be terminated, because otherwise it could interfere with the next run. So I put a `.kill()` on the command in the `finally` block. This hangs in the first Ctrl+C, and doesn't kill the subprocess on the second.

Here's the stack trace:

```
^CTraceback (most recent call last):
  File "ci/run_benchmarks.py", line 123, in _run_benchmarks
    for line in benchmark_cmd:
  File "/usr/local/lib/python3.5/dist-packages/sh.py", line 857, in next
    chunk = self.process._pipe_queue.get(True, 0.001)
  File "/usr/lib/python3.5/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.5/threading.py", line 297, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ci/run_benchmarks.py", line 192, in <module>
    _split_strip_csv(args.benchmark_blacklist))
  File "ci/run_benchmarks.py", line 142, in _run_benchmarks
    if benchmark_cmd:
  File "/usr/local/lib/python3.5/dist-packages/sh.py", line 835, in __len__
    return len(str(self))
  File "/usr/local/lib/python3.5/dist-packages/sh.py", line 884, in __str__
    return self.__unicode__()
  File "/usr/local/lib/python3.5/dist-packages/sh.py", line 891, in __unicode__
    if self.process and self.stdout:
  File "/usr/local/lib/python3.5/dist-packages/sh.py", line 820, in stdout
    self.wait()
  File "/usr/local/lib/python3.5/dist-packages/sh.py", line 784, in wait
    exit_code = self.process.wait()
  File "/usr/local/lib/python3.5/dist-packages/sh.py", line 2354, in wait
    pid, exit_code = no_interrupt(os.waitpid, self.pid, 0) # blocks
  File "/usr/local/lib/python3.5/dist-packages/sh.py", line 1666, in no_interrupt
    ret = syscall(*args, **kwargs)
```

**Comment by amoffat** [comment]
Can you post a small reproducible sample of code?

**Comment by dmitry-xnor** [comment]
```python
#!/usr/bin/env python3

import sh

if __name__ == "__main__":
    cmd = None
    try:
        cmd = sh.sleep("15m", _iter=True)
        for l in cmd:
            pass
    finally:
        if cmd:
            cmd.kill()
```

**Comment by amoffat** [comment]
Ok, I see what's happening here.  The problem is the `if cmd` line.  That is evaluating the cmd object, which implicitly waits for the command to finish, in order to get the full output of the command and perform `len()` on it (to test if its non-zero).  If you change it to `if cmd is not None`, you'll just test the identity of the `cmd` name, and not evaluate it, and everything should work as you want.

**Comment by dmitry-xnor** [comment]
Facepalm. Thanks for your help. I hope this helps someone else. :-)

**Comment by amoffat** [comment]
Cool :+1: This isn't the first time that a command object behaving too much like a string has bitten someone.  If it bites many more people, it might have to change
