### ISSUE TITLE
sh swallows stdout/err when exit code is non-zero

### ISSUE THREAD

**Issue by vickychijwani** [amoffat/sh#391]
Here's an example:

```console
$ cat shbin.py
#!/usr/bin/env python2
from __future__ import print_function
import sys
print("You should see this on stdout")
print("You should see this on stderr", file=sys.stderr)
sys.exit(1)
$ ln -s /tmp/shbin.py /usr/local/bin/shbin  # let's put this on $PATH...
$ pip list | grep sh
sh (1.12.14)
$ cat shtest.py
import sh, StringIO
buf = StringIO.StringIO()
sh.shbin(_out=buf, _err=buf)
print buf.getvalue()
$ python shtest.py  # swallows stdout and stderr
Traceback (most recent call last):
  File "./shtest.py", line 4, in <module>
    sh.shbin(_out=buf, _err=buf)
  File "/spare/local/vchijwani/conda/envs/shtest/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/spare/local/vchijwani/conda/envs/shtest/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/spare/local/vchijwani/conda/envs/shtest/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/spare/local/vchijwani/conda/envs/shtest/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/shbin

  STDOUT:


  STDERR:

```

As you can see, `sh` swallows the output.

EDIT: for completeness' sake, here's another example showing output redirection works fine for successful (zero exit code) commands:
```console
$ cat shbin.py  # note: removed sys.exit(1)
#!/usr/bin/env python2
from __future__ import print_function
import sys
print("You should see this on stdout")
print("You should see this on stderr", file=sys.stderr)
$ python shtest.py 
You should see this on stderr
You should see this on stdout

```

**Comment by vickychijwani** [comment]
It appears this regression happened sometime between versions 1.6 and 1.7. With 1.7 I get the same output as above, but with 1.6 I see the expected output:

```
Traceback (most recent call last):
  File "./shtest.py", line 4, in <module>
    sh.shbin(_out=buf, _err=buf)
  File "/home/vicky/.local/lib/python2.7/site-packages/sh.py", line 625, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/vicky/.local/lib/python2.7/site-packages/sh.py", line 262, in __init__
    self.wait()
  File "/home/vicky/.local/lib/python2.7/site-packages/sh.py", line 266, in wait
    self._handle_exit_code(self.process.wait())
  File "/home/vicky/.local/lib/python2.7/site-packages/sh.py", line 275, in _handle_exit_code
    self.process.stderr
sh.ErrorReturnCode_1: 

  RAN: '/usr/local/bin/shbin'

  STDOUT:
You should see this on stdout


  STDERR:
You should see this on stderr
```

**Comment by vickychijwani** [comment]
I ran a `git bisect` and this seems to be the commit that introduced the regression:

```
commit b1357d1f56ac9539666621fe3f85435a6867eefb
Author: Andrew Moffat <andrew.robert.moffat@gmail.com>
Date:   Tue Nov 20 21:32:47 2012 -0600

    added 'tee' special keyword argument

:100644 100644 1a1ecd8f47889337ee519890aa9ea685639ccd23 784215265c5bf12ef8945711b49e6a9aa38ade44 M	sh.py
:100644 100644 c0cd319b2ec1d58822ca7864a4f9db4e7d85ef8c 75276b9546b33a98b43fdda907327fa28848ab59 M	test.py
```

**Comment by vickychijwani** [comment]
Just realized this was an intended behaviour change for the [`tee`](http://amoffat.github.io/sh/sections/special_arguments.html#tee) feature 😅. Sorry for the false alarm!

PS: is there a way to tee both stdout and stderr? Looks like setting `tee` to `True` or `"out"` affects only stdout, while `tee="err"` affects only stderr.

**Comment by amoffat** [comment]
Hi @vickychijwani, take a look at https://github.com/amoffat/sh/issues/215

**Comment by vickychijwani** [comment]
Thanks, I can use that workaround. I'd like to add that `sh`'s behaviour could be improved when output has been redirected and so not available in internal buffers. This would avoid confusion like the above. For example:

```
Traceback (most recent call last):
  File "./shtest.py", line 4, in <module>
    sh.shbin(_out=buf, _err=buf)
  File "/spare/local/vchijwani/conda/envs/shtest/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/spare/local/vchijwani/conda/envs/shtest/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/spare/local/vchijwani/conda/envs/shtest/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/spare/local/vchijwani/conda/envs/shtest/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: '/usr/local/bin/shbin'

  STDOUT and STDERR are not available because output redirection is enabled. Use the _tee option to see the output here while also redirecting.
```

If you like this suggestion, I could create a new issue for this so it can be addressed later.
