### ISSUE TITLE
Background processes need their own _out arg

### ISSUE THREAD

**Issue by paul-hammant** [amoffat/sh#408]
I'm using py.sh in integrations tests -  and one of those kills a process to see how the system handles that, and recovers.  In the middle of the test output, I see:

```
Exception in thread background thread for pid 41686:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sh.py", line 2455, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.6/site-packages/sh.py", line 2153, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.SignalException_SIGKILL: 
```

I'd like to be able to slurp that into a StringIO and assert that it's what I expect. Well approximately, given line numbers change over time.

So I don't really know, but would a `_bg_out` and `_bg_err_to_out` do it?

**Comment by amoffat** [comment]
I would advise setting [_bg_exc](https://amoffat.github.io/sh/sections/special_arguments.html#bg-exc) to `False` to suppress the exception from the background thread, and then call `p.wait()` on your recently-killed process. This will bubble the background exception up in the main thread, where you can examine it however you like.
