### ISSUE TITLE
*** TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by davisem** [amoffat/sh#422]
Trying to use the _env parameter (very cool btw), but am seeing this error:
```
Python 3.6.2 (default, Jul 17 2017, 16:44:45)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sh
>>> from io import StringIO
>>>
>>> buf = StringIO()
>>> sh2 = sh(_out=buf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/sh.py", line 3367, in __call__
    code = parent[4][0].strip()
TypeError: 'NoneType' object is not subscriptable
```

I was also hoping I could do something like:
```
>>> my_env = {'PATH': 'somepath'}
>>> sh2 = sh(_env=my_env)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/sh.py", line 3367, in __call__
    code = parent[4][0].strip()
TypeError: 'NoneType' object is not subscriptable
```

**Comment by amoffat** [comment]
Hmm..it looks like you've caught an edge case from some XTREME sh magic being used.  I bet what you're doing will work in a python script file, even if it doesn't work on the python console.  Give it a try.

**Comment by davisem** [comment]
Truly magical. Thank you for you help, and for the awesome module. Long live sh!

**Comment by amoffat** [comment]
Np.  Let's leave this issue open until I fix the underlying bug :+1:

**Comment by ddstreet** [comment]
@amoffat are you still maintaining this pkg?  This still isn't fixed...
