### ISSUE TITLE
sh(_env=env) for bash scripts?

### ISSUE THREAD

**Issue by davisem** [amoffat/sh#423]
I've gotten this approach to work with other executables, i.e. loading gcc compiler versions. But I can't get it to work with bash scripts. Something I'm not understanding?
```
cat myscript.sh
#!/usr/bin/env bash
echo "MYSCRIPT RAN"
```
```
import sh
import os

if __name__ == '__main__':
    env = os.environ.copy()
    env['PATH'] = '/home:' + env['PATH']
    sh2 = sh(_env=env)
    sh2.myscript.sh()
```

```Traceback (most recent call last):
  File "test_myscript.py", line 8, in <module>
    sh2.myscript.sh()
  File "/home/.local/lib/python3.5/site-packages/sh.py", line 3349, in __getattr__
    return self.__env[name]
  File "/home/.local/lib/python3.5/site-packages/sh.py", line 3226, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: myscript
```

**Comment by retr0h** [comment]
Was about to report this very issue.

**Comment by davisem** [comment]
Nice. Maybe this will get some attention then. It's a super cool feature. Would love to use it.

**Comment by amoffat** [comment]
`_env` is what is sent to the process.  If you want to find `myscript`, edit `os.environ` in place, instead of in a copy.  Or better yet, provide a full path to a https://amoffat.github.io/sh/sections/command_class.html#command-class

```python
import sh
myscript = sh.Command("path/to/myscript.sh")
myscript()
```

**Comment by davisem** [comment]
Ok that makes sense. Thanks for the explanation.
