### ISSUE TITLE
Overriding default arguments for all command fails

### ISSUE THREAD

**Issue by hirenvadalia** [amoffat/sh#440]
As mentioned in https://amoffat.github.io/sh/sections/default_arguments.html#default-arguments, overriding default arguments for all further command fails as below:
```python
>>> import sh
>>> from io import StringIO
>>> buf = StringIO()
>>> sh2 = sh(_out=buf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/sh.py", line 3367, in __call__
    code = parent[4][0].strip()
TypeError: 'NoneType' object has no attribute '__getitem__'
>>> 
```

And after adding below two line at 3368 (after `parent = inspect.stack()[1])` it worked:
```
if parent[4] is None:
    return new_mod
```

**Comment by guyskk** [comment]
I meet the same error:

```python
>>> import sh
>>> from io import StringIO
>>> 
>>> buf = StringIO()
>>> sh2 = sh(_out=buf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guyskk/.pyenv/versions/rssant/lib/python3.6/site-packages/sh.py", line 3367, in __call__
    code = parent[4][0].strip()
TypeError: 'NoneType' object is not subscriptable
>>> 
>>> sh.__version__
'1.12.14'
```
Python version `Python 3.6.6`  
OS `Linux archlinux 4.17.4-1-ARCH #1 SMP PREEMPT Tue Jul 3 15:45:09 UTC 2018 x86_64 GNU/Linux`

**Comment by amoffat** [comment]
https://github.com/amoffat/sh/pull/466 fixes this and will go out with the next release.
