### ISSUE TITLE
How to avoid crash when resizing the terminal window?

### ISSUE THREAD

**Issue by danijar** [amoffat/sh#442]
I have a Python script that runs several commands using sh.py with `_fg=True`. When resizing the terminal window while the script is running, it crashes with this stack trace:

```
Traceback (most recent call last):
  ...
  File "/home/danijar/.local/lib/python2.7/site-packages/sh.py", line 1404, in __call__
    exit_code = launch()
  File "/home/danijar/.local/lib/python2.7/site-packages/sh.py", line 1400, in <lambda>
    launch = lambda: os.spawnv(os.P_WAIT, cmd[0], cmd)
  File "/usr/lib/python2.7/os.py", line 565, in spawnv
    return _spawnvef(mode, file, args, None, execv)
  File "/usr/lib/python2.7/os.py", line 548, in _spawnvef
    wpid, sts = waitpid(pid, 0)
OSError: [Errno 4] Interrupted system call
```

How can I avoid the script from crashing when the terminal window is resized? Is this expected?

I'm using Ubuntu with urxvt-unicode terminal.

**Comment by amoffat** [comment]
This looks like a shortcoming with python < 3. Details https://www.python.org/dev/peps/pep-0475/
