### ISSUE TITLE
help(sh) does not work

### ISSUE THREAD

**Issue by sushsada** [amoffat/sh#455]
As this is my first time using 'sh', I tried to run help on it. 'sh' doesnt seem to like it

```
sh $python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sh
>>> help(sh)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sush/anaconda3/lib/python3.6/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/Users/sush/anaconda3/lib/python3.6/pydoc.py", line 1858, in __call__
    self.help(request)
  File "/Users/sush/anaconda3/lib/python3.6/pydoc.py", line 1911, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/Users/sush/anaconda3/lib/python3.6/pydoc.py", line 1645, in doc
    pager(render_doc(thing, title, forceload))
  File "/Users/sush/anaconda3/lib/python3.6/pydoc.py", line 1638, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/Users/sush/anaconda3/lib/python3.6/pydoc.py", line 382, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/Users/sush/anaconda3/lib/python3.6/pydoc.py", line 1103, in docmodule
    all = getattr(object, '__all__', None)
  File "/Users/sush/Desktop/up/sh/sh.py", line 3349, in __getattr__
    return self.__env[name]
  File "/Users/sush/Desktop/up/sh/sh.py", line 3187, in __getitem__
    Please import sh or import programs individually.")
RuntimeError: Cannot import * from sh. Please import sh or import programs individually.
>>> 
```

**Comment by amoffat** [comment]
Thanks for reporting. 1a56211350ad309df9123dd53e40150d5a395888 will go out in the next release.
