### ISSUE TITLE
wrong type for _env leads to confusing error

### ISSUE THREAD

**Issue by bulma-capsule** [amoffat/sh#460]
When the type of **_env** is a **set** instead of a **dict** (a common error when using a coma instead of a colon), the error raised suggests the command itself failed and does not hint that the type of the **_env** argument is incorrect.

```python
>>> sh.env(_env={'FOO': 'bar'})
FOO=bar

>>> sh.env(_env={'FOO', 'bar'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/venv/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/venv/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/home/venv/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/venv/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_255: 

  RAN: /usr/bin/env

  STDOUT:


  STDERR:
```

**Comment by singuliere** [comment]
ran into the same error today

**Comment by ecederstrand** [comment]
Also hit this, but this time it was a bit more sneaky. All values in the env dict must be strings:

```python
>>> from sh import ls
>>> ls(_env={'MY_VALUE': "100"})
README.md
>>> ls(_env={'MY_VALUE': 100})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "lib/python3.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "lib/python3.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_255: 

  RAN: /bin/ls

  STDOUT:


  STDERR:

```
