### ISSUE TITLE
ImportError: cannot import name pew

### ISSUE THREAD

**Issue by thoongnv** [amoffat/sh#487]
I got ImportError
I'm got above error in:
MacOS: Python 2.7.10
Ubuntu: Python 2.7.15+

Also ImportError: cannot import name pythonz
```
Python 2.7.10 (default, Feb 22 2019, 21:55:15) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sh import pew
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name pew
>>> from sh import pythonz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name pythonz
```

Here is my `sh` module version
```
pip freeze | grep sh
backports.shutil-get-terminal-size==1.0.0
sh==1.12.14
shutilwhich==1.1.0
```

**Comment by thoongnv** [comment]
I found out the problem is missing `pew` and `pythonz` package in my system.

**Comment by midacts** [comment]
Thanks for this issue.
I was running into this as well trying to import some postgresql commands.

I needed to install the postgresql-client first.
