### ISSUE TITLE
how to fix stacktrace with sh.SignalException_SIGKILL 

### ISSUE THREAD

**Issue by ggmartins** [amoffat/sh#535]
Hey @amoffat thanks for your great work with sh. I'm really close to getting a solid code parsing tail output, are there ways to catch or suppress the stack trace that comes with an attempt to kill a _tail_ blocked with .next() ? I've been trying to catch this exception on both _kill_ and _next_ calls but the beautiful stack trace keeps showing.  Let me know if there's an alternative to this code. Thanks a lot!

```
           #elsewhere in the code
           try:
             filestatus[filename]['running'] = False #this is not enough as sh.tail is blocking at .next()
             tail = filestatus[event.src_path]['tail']
             tail.kill()
           except sh.SignalException_SIGKILL as e:
             print(str(e))

...
              #elsewhere in the code
              t = threading.Thread(target=process_tmp_ta, args=(f,)) #f == /tmp/tmp.074461843
              filestatus[f] = {}
              filestatus[f]['thread'] = t
              t.start()

def process_tmp_ta(filename=""):
      filestatus[filename]['running'] = True
      filestatus[filename]['tail'] = sh.tail("-F", filename, _iter=True)
      while filestatus[filename]['running']:
        print("running")
        try:
               line = filestatus[filename]['tail'].next()
        except sh.SignalException_SIGKILL as e:
            print("process_tmp_ta tail terminated")
            break
```

```
Exception in thread background thread for pid 3185:
Traceback (most recent call last):
  File "/Users/[REDACTED]/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/[REDACTED]/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/[REDACTED]/src/github.com/[REDACTED]/scripts/venv/lib/python3.7/site-packages/sh.py", line 1662, in wrap
    fn(*args, **kwargs)
  File "/Users/[REDACTED]/src/github.com/[REDACTED]/venv/lib/python3.7/site-packages/sh.py", line 2606, in background_thread
    handle_exit_code(exit_code)
  File "/[REDACTED]/src/github.com[REDACTED]/scripts/venv/lib/python3.7/site-packages/sh.py", line 2304, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/[REDACTED]/src/github.com/[REDACTED]/scripts/venv/lib/python3.7/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.SignalException_SIGKILL: 

  RAN: /usr/bin/tail -F /tmp/tmp.074461843

  STDOUT:
[REDACTED]
  STDERR:
```

**Comment by amoffat** [comment]
Hi @ggmartins, It looks like [`_bg_exc=False`](http://amoffat.github.io/sh/sections/special_arguments.html#bg-exc) is the magic incantation you're looking for. It will force background exceptions to not happen in the background thread, but instead in the main thread, where your try/except code can catch them. Give that a try and let me know if that works.

**Comment by ggmartins** [comment]
yes, it's working perfectly now. Thanks a lot!
