### ISSUE TITLE
module 'sh.contrib' has no attribute 'sudo'

### ISSUE THREAD

**Issue by zillionare** [amoffat/sh#562]
sh version is 1.14.1, python is 3.8.5/3.8.8

```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sh
>>> sh.contrib
<module 'sh.contrib'>
>>> sh.contrib.sudo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sh.contrib' has no attribute 'sudo'
>>> sh.sudo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/omega/lib/python3.8/site-packages/sh.py", line 3518, in __getattr__
    return self.__env[name]
  File "/conda/envs/omega/lib/python3.8/site-packages/sh.py", line 3316, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: sudo
```

both sh.contrib.sudo and sh.sudo broke.

**Comment by zillionare** [comment]
sometimes it seems work, sometimes fail. But always fail in unittest.mock:

```
ERROR: test_config_logging (test_cli.TestCLI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/conda/envs/omega/lib/python3.8/unittest/async_case.py", line 65, in _callTestMethod
    self._callMaybeAsync(method)
  File "/conda/envs/omega/lib/python3.8/unittest/async_case.py", line 84, in _callMaybeAsync
    ret = func(*args, **kwargs)
  File "/apps/omega/tests/test_cli.py", line 165, in test_config_logging
    with mock.patch("sh.contrib.sudo.mkdir", create=True):
  File "/conda/envs/omega/lib/python3.8/unittest/mock.py", line 1377, in __enter__
    self.target = self.getter()
  File "/conda/envs/omega/lib/python3.8/unittest/mock.py", line 1552, in <lambda>
    getter = lambda: _importer(target)
  File "/conda/envs/omega/lib/python3.8/unittest/mock.py", line 1228, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/conda/envs/omega/lib/python3.8/unittest/mock.py", line 1217, in _dot_lookup
    __import__(import_path)
ModuleNotFoundError: No module named 'sh.contrib.sudo'; 'sh.contrib' is not a package
```

the code worked before, I don't know why it breaks recently.

**Comment by ecederstrand** [comment]
Do you in fact have the `sudo` command available on this system and reachable in your PATH? What does `which sudo` output?

**Comment by ecederstrand** [comment]
I'm closing this due to OP timeout. Feel free to reopen if you get back to this issue.
