### ISSUE TITLE
Issues running command with regex args

### ISSUE THREAD

**Issue by sanzenwin** [amoffat/sh#567]
```
import sh

print(sh.__version__)
sh.mkdir('-p', '/test')
sh.mkdir('-p', '/test2')
sh.cp('-rfp', '/test/*', '/test2')
```

```
'1.14.1'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 1520, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 784, in __init__
    self.wait()
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 841, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /bin/cp -rfp '/test/*' /test2

  STDOUT:


  STDERR:
/bin/cp: cannot stat '/test/*': No such file or directory

```

**Comment by amoffat** [comment]
https://amoffat.github.io/sh/sections/faq.html#why-doesn-t-work-as-a-command-argument

**Comment by sanzenwin** [comment]
@amoffat, thanks a lot.
