### ISSUE TITLE
pipes/redirect usage question

### ISSUE THREAD

**Issue by michaelaye** [amoffat/sh#595]
Thanks for your great module!

I'd like to pipe several commands' output together and eventually redirect (pipe?) directly into a numpy array without a temporary file first.

For finding the correct pipe/redirect settings with `subprocess` I created a temporary file `myfile.pipe`.
To find the structure of the binary stream I first need to read a structure descriptor from the beginning of the stream:

```python
def get_token(s):
    s = s.strip().strip("'").strip().strip("'").strip()
    return s

def read_descriptor_header(stream):
    d = OrderedDict()
    while True:
        line = stream.readline()
        noOfChars = len(line)
        # short descriptors have 54 chars
        if noOfChars == 54:
            tmp = get_token(line.decode())
        # long descriptor names have 134 chars
        elif noOfChars == 134:
            longdes = get_token(line.decode())
            d[tmp] = longdes
        elif noOfChars == 15:
            break
    return d
```
I then can stream the output of `cat` directly into numpy like so:

```python
proc = sp.Popen("cat myfile.pipe", stdout=sp.PIPE, shell=True)
dic = read_descriptor_header(proc.stdout)
dtype = np.dtype([(key, "f8") for key in dic.keys()])
arr = np.frombuffer(proc.stdout.read(), dtype=dtype)
```

I then tried to do this using `sh.cat` and a callable for `_out`, but I just can't find the right combo with _out_bufsize, _iter, and _piped to make things work.

Here's my callable:

```python
def process_sh_pipe(stream):
    d = read_descriptor_header(stream)
    dtype = get_dtype(d)
    return pd.DataFrame(np.frombuffer(stream, dtype=dtype))
```
and several use trials:

```python
from sh import cat

cat("myfile.pipe", _out=process_sh_pipe)

Exception in thread STDOUT/ERR thread for pid 18385:
Traceback (most recent call last):
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 1662, in wrap
    fn(*args, **kwargs)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 2631, in output_thread
    done = f.read()
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 3096, in read
    self.write_chunk(chunk)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 3071, in write_chunk
    self.should_quit = self.process_chunk(chunk)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 2992, in process
    return handler(chunk)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 1746, in fn
    return handler(chunk, *args)
  File "/tmp/ipykernel_14886/1519246122.py", line 2, in process_sh_pipe
  File "/tmp/ipykernel_14886/3174323839.py", line 11, in read_descriptor_header
AttributeError: 'str' object has no attribute 'readline'
```

```python
cat("myfile.pipe", _out=process_sh_pipe, _out_bufsize=0)
```
hangs....

```python
cat("myfile.pipe", _out=process_sh_pipe, _piped=True)
```
hangs...

```python
cat("myfile.pipe", _out=process_sh_pipe, _iter=True)

Exception in thread STDOUT/ERR thread for pid 18426:
Traceback (most recent call last):
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 1662, in wrap
    fn(*args, **kwargs)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 2631, in output_thread
    done = f.read()
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 3096, in read
    self.write_chunk(chunk)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 3071, in write_chunk
    self.should_quit = self.process_chunk(chunk)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 2992, in process
    return handler(chunk)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 1746, in fn
    return handler(chunk, *args)
  File "/tmp/ipykernel_14886/1519246122.py", line 2, in process_sh_pipe
  File "/tmp/ipykernel_14886/3174323839.py", line 11, in read_descriptor_header
AttributeError: 'str' object has no attribute 'readline'
```

```python
cat("myfile.pipe", _out=process_sh_pipe, _iter=True, _piped=True)
```
hangs...

```python
cat("myfile.pipe", _out=process_sh_pipe, _iter=True, _out_bufsize=0)

Exception in thread STDOUT/ERR thread for pid 18507:
Traceback (most recent call last):
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 1662, in wrap
    fn(*args, **kwargs)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 2631, in output_thread
    done = f.read()
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 3096, in read
    self.write_chunk(chunk)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 3071, in write_chunk
    self.should_quit = self.process_chunk(chunk)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 2992, in process
    return handler(chunk)
  File "/luna9/maye/mambaforge/envs/py38/lib/python3.8/site-packages/sh.py", line 1746, in fn
    return handler(chunk, *args)
  File "/tmp/ipykernel_14886/1519246122.py", line 2, in process_sh_pipe
  File "/tmp/ipykernel_14886/3174323839.py", line 11, in read_descriptor_header
AttributeError: 'str' object has no attribute 'readline'
```

I feel like there's something fundamental I'm not understanding what I am getting from the redirection from `sh.py`, sorry about that.

At the end, I like to create a pipeline like so:

```python
arr = last_pipe(pipe2(pipe1(args), args), _out=process_sh_pipe)
```

Hopefully this all makes sense?
Thanks for any help!

**Comment by michaelaye** [comment]
Maybe the problem exists, because I need both, first a line-based reading first for the descriptor (unfortunately dynamic size), and then a binary stream without any newline stops?

**Comment by amoffat** [comment]
There won't be a `.readline()` method on your string no matter what buffering you use, so you'll need to read up until the newline yourself, or set the buffering to 1, but as you mention, then you'll need to switch back to regular buffering or unbuffered to read your binary data. This is possible using an undocumented api [here](https://github.com/amoffat/sh/blob/develop/sh.py#L2342-L2349). You can call those methods on the process that is passed to your out callback. See [this function signature](https://amoffat.github.io/sh/sections/redirection.html#id2)

With regards to `_piped=True`, the command that has that argument set must also be contained inside an outer command for it to work properly. The only thing that `_piped` really does is tell the inner command to not complete, and tells the outer command to wire up the stdout -> stdin correctly. See the examples here https://amoffat.github.io/sh/sections/piping.html?highlight=piped#advanced

**Comment by michaelaye** [comment]
Thx for your help! Unfortunately, the function signature of `fn(data, stdin_queue, process)` with `process` relating to some "weakref.weakref to the OProc object." is completely over my head, not understanding a word or how to use it. I guess I'll just wrap my above solution into my own wrapper for piping.
For the interested reader, here's how one can pipe things together with the `sp.Popen` approach (adapted from subprocess docs):

```python
import subprocess as sp

def cmd1(args):
    "args is a list of cmd options"
    return sp.Popen(["cmd1"] + args, stdout=sp.PIPE)

def cmd2(cmd1_args, cmd2_args):
    p1 = cmd1(cmd1_args)
    p2 = sp.Popen(["cmd2"] + cmd2_args, stdin=p1.stdout, stdout=sb.PIPE)
    p1.stdout.close()
    return p2

pipe = cmd2(p1_args, p2_args)
results = pipe.communicate()[0]
```
