### ISSUE TITLE
Run as root but still needs sudo

### ISSUE THREAD

**Issue by heliumsea** [amoffat/sh#617]
I wrote a script containing "iptables xxx". 
iptables is only in /usr/sbin.
I added "whoami" at the beginning of the scirpt and got the result "root", however, I still got error that "need sudo".

Here is the script:
```bash
#!/bin/bash
# establish connection with ckpt hdfs
whoami
set_hdfs_iptables () {
  iptables -t nat -A OUTPUT -d $1 -p tcp --dport 9000 -j DNAT --to-destination $2
}

set_hdfs_iptables 10.215.131.170 9.37.164.196:39001
set_hdfs_iptables 10.196.145.165 9.37.164.196:39002
set_hdfs_iptables 100.76.65.66 9.37.164.196:39003
```

I ran it by
```python
hdfs_iptables_sh = sh.Command("/opt/dl/hdfs_iptables.sh")
hdfs_iptables_sh()
```

**Comment by amoffat** [comment]
Please post the raw output of the command running via sh, and also directly from bash in the terminal.

**Comment by heliumsea** [comment]
```
2022-08-09 04:44:56 - [INFO] Setup HDFS
2022-08-09 04:44:56 - [INFO] <Command '/opt/dl/hdfs_iptables.sh', pid 365>: process started
Traceback (most recent call last):
  File "/opt/dl/start.py", line 161, in <module>
    main()
  File "/opt/dl/start.py", line 129, in main
    setup_hdfs()
  File "/opt/dl/start.py", line 85, in setup_hdfs
    hdfs_iptables_sh()
  File "/usr/local/lib/python3.8/site-packages/sh.py", line 1566, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.8/site-packages/sh.py", line 822, in __init__
    self.wait()
  File "/usr/local/lib/python3.8/site-packages/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.8/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_3: 

  RAN: /opt/dl/hdfs_iptables.sh

  STDOUT:
root


  STDERR:
iptables v1.4.21: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.4.21: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
```

**Comment by amoffat** [comment]
And the output from when you run your script from the terminal?

**Comment by heliumsea** [comment]
It's interesting that it still showed "need root" when I ran it in bash.
I can run the command directly in bash but can't run the command within scripts.

I solved the problem by running "subprocess.Popen(["bash", "/root/hdfs_iptables.sh"])".

I don't understand why it worked... You must have much knowledge about python and bash. Could you please explain it?
Thanks a lot.
