### ISSUE TITLE
test_tty_input/test_tty_stdin fails on OpenIndiana

### ISSUE THREAD

**Issue by mtelka** [amoffat/sh#672]
I see following two test failures on OpenIndiana related to `termios.tcgetattr()`:
```
======================================================================
ERROR: test_tty_input (tests.test.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$(BUILD_DIR)/tests/test.py", line 2182, in test_tty_input
    pw_stars = python(py.name, _tty_in=True, _out=password_enterer)
  File "$(BUILD_DIR)/sh.py", line 1524, in __call__
    rc = self.__class__.RunningCommandCls(cmd, call_args, stdin, stdout, stderr)
  File "$(BUILD_DIR)/sh.py", line 733, in __init__
    self.process = OProc(
  File "$(BUILD_DIR)/sh.py", line 2228, in __init__
    attr = termios.tcgetattr(self._stdin_parent_fd)
termios.error: (22, 'Invalid argument')

======================================================================
ERROR: test_tty_stdin (tests.test.FunctionalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$(BUILD_DIR)/tests/test.py", line 2432, in test_tty_stdin
    out = pythons(py.name, _in="test\n", _tty_in=True)
  File "$(BUILD_DIR)/sh.py", line 1524, in __call__
    rc = self.__class__.RunningCommandCls(cmd, call_args, stdin, stdout, stderr)
  File "$(BUILD_DIR)/sh.py", line 733, in __init__
    self.process = OProc(
  File "$(BUILD_DIR)/sh.py", line 2228, in __init__
    attr = termios.tcgetattr(self._stdin_parent_fd)
termios.error: (22, 'Invalid argument')
```

**Comment by amoffat** [comment]
Marking this as closed until OpenIndiana is better supported. I am open to accepting PRs that provide this support.

**Comment by mtelka** [comment]
This seems to be related: #143
